### PR TITLE
bugfix: when utxos are not enough

### LINKED ISSUE #1: Invalid selection for insufficient funds
Hi Bruno, thanks for your work in porting this library.  Unfortunelly it doesn't seem to work correctly.
When the available utxos are not sufficient for the output, the library returns invalid selection instead of no selection at all, and also the feeRate is negative.
```
    test("Insufficient funds result in an empty array", () => {
       const utxos =
           [
               {
                   "txId": "0eb727d9da3cbbabae776d8200221f68473d5a0bc2c456d18e419c493ed0bf2d",
                   "vout": 46,
                   "value": 14561,
               },
               {
                   "txId": "d4eb4955286bb97c40302b5ec018b55f9b498f2b64ce726f19b0eadb7f4a7c44",
                   "vout": 80,
                   "value": 355933,
               }
           ];

       const recipients = [
               {
                   "value": 69036119,
                   "to": "1GsPMkp9dr1nHYoXzuBitiCiGcDzAuhnB5",
               }
       ];

        const { inputs, outputs } = coinselection(utxos, recipients, 5, 1);
        expect(inputs.length).toEqual(0);
        expect(outputs.length).toEqual(0);
    });
```
All three strategies return invalid selection. Am I missing something here or is this a bug?

### PR DESCRIPTION
**Pull request by brunoerg**
Fixes #1

### CODE REVIEW

**Comment by gpa** [comment]
I'm still getting invalid selections, but now its related to the long_term_fee parameter.
```
    test("", () => {
            const recipients = [
                {
                    "value": 78544099,
                    "to": "1DLvZKke9UXK2QwaxnPzQ3Mh8YHu7TsKjS",
                }
            ];
            const utxos = [
            {
                "txId": "7ee0dd32d14fc462e623a5d1cfe38f7412a2f740427f778166131ac9e7950158",
                "vout": 75,
                "value": 864351
            },
            {
                "txId": "2d62424ade769d7f7841d03966877a306e2c039930cbbad36ea3bb6cdf378350",
                "vout": 59,
                "value": 5059
            },
            {
                "txId": "6317f465f13cfd6b907d0715c5bb0f2d87d6f83d14699387f6d39ebbfc453747",
                "vout": 34,
                "value": 1278831
            },
            {
                "txId": "0cdde4f3f5b729642327050b9c9348975b74a9bd8771654c475ea008d527c358",
                "vout": 67,
                "value": 105841088
            },
            {
                "txId": "d78b14b7a40aff897210bbd158687c1c6efefa73515445d16e0ea687ce110cf2",
                "vout": 12,
                "value": 384570
            },
            {
                "txId": "8dfa2f40aca062258aec0f365795a685502beda329d5e7c55db266c955ae1e75",
                "vout": 71,
                "value": 121959
            },
            {
                "txId": "084f26d41457c683d08f78e3bea96e4978f715d912aaf4ec2e55a4baf7abdd60",
                "vout": 29,
                "value": 1063197
            },
            {
                "txId": "3072d49285ac92004f70e091d02cb3fbeefb8127cb6165795a31269462d0f347",
                "vout": 8,
                "value": 1292976
            },
            {
                "txId": "0711f8a8745d6e584c585cb5bfbecd7b85acec4e8281c21b9f354b3b0992533a",
                "vout": 50,
                "value": 1523048
            },
            {
                "txId": "11e8e5901baa2a7eac37d192bbaf20c63ac54b9bffc66b86ef47d130f95fe3f8",
                "vout": 87,
                "value": 116444705
            },
            {
                "txId": "34cceb022593edde49d9d4075060cf32e9323d84c865210098012eacadb8773c",
                "vout": 36,
                "value": 9336
            },
            {
                "txId": "43ceadd80743f7133768e1d9eae5c673c9c1a16621924a6bd0aa996f3a04384c",
                "vout": 29,
                "value": 1192622
            },
            {
                "txId": "fce7846e1b9eff68e777853462b22a04d1f67b690119c4eec89c1aa2f545f9a5",
                "vout": 88,
                "value": 423376
            },
            {
                "txId": "1b0bb27a82a93a0fb60dcac10a882769a8d7199d563b48d93213b0c6736cd897",
                "vout": 19,
                "value": 559328
            },
            {
                "txId": "62590fb8d0f6e04692ce9c8b1f96c4e1dc9192a3fbc19bf824b983b17c458b98",
                "vout": 97,
                "value": 3541
            },
            {
                "txId": "280b6d048c2aa681bcd527148496620533d8eef11ee98edda25981cdd3628a1b",
                "vout": 11,
                "value": 741267
            },
            {
                "txId": "ce6547e727f9e20901a8abfa383d7d8b70e0bc5692d88d9c174f4d9806eecf63",
                "vout": 74,
                "value": 1431470
            },
            {
                "txId": "b657b66deefdca5f7b640811d9e3c90e78f3761be6971b7f9e06dbccf625a643",
                "vout": 51,
                "value": 7049
            },
            {
                "txId": "cdc3450c5e41552270fdc60e87b4fe7fc66f978b9e6791009923581100521902",
                "vout": 54,
                "value": 15380
            },
            {
                "txId": "a54cc2feb63a08da3c9946ec0d930d695c0f1cabf10d4bae4b4bb7b12b58c23f",
                "vout": 31,
                "value": 1981645
            },
            {
                "txId": "8dfe00450a29db2609e21597ee9cd1335ccd4af6d0cae77c0ab429043e4fe913",
                "vout": 37,
                "value": 72795249
            },
            {
                "txId": "ccf742c8edb0020717c179c8bac3efe28498700c4f532b7333fe57e6eedade49",
                "vout": 97,
                "value": 7095
            },
            {
                "txId": "5aa27f69208949188e9de652bf905e307403f4929a96d7f3f6de64b89310de84",
                "vout": 11,
                "value": 6260
            },
            {
                "txId": "116d88f50fba2c5bf0bb1be8080ece41dc4df867809d7d5055bcbae34cdf89d4",
                "vout": 89,
                "value": 511317
            },
            {
                "txId": "0d1efec7bdc4ed9845265e9ed18b0e9ac19c378009214adeafcaf36ca5b002ec",
                "vout": 51,
                "value": 663794
            },
            {
                "txId": "d639c97b14f2c0f0016c0cba7bf75fd61519dd1c507213f29499a4ea96774894",
                "vout": 40,
                "value": 15657
            },
            {
                "txId": "da4ab79aa34f3ac6b60618a366560c6d7d21d851198161703c156a3fbfd77c38",
                "vout": 63,
                "value": 82035389
            },
            {
                "txId": "05ab5d7308333a82bc5b2b806d438e66c9e6648aac490d90e9c32ac12615fc96",
                "vout": 27,
                "value": 301810
            },
            {
                "txId": "443cd864ef20f95bb262301b2da801372adb552220472362526f5b3aa8755d4e",
                "vout": 87,
                "value": 7846
            },
            {
                "txId": "4da51480c21ce1e0deab0578e7fd470d6025cccdf4c69d3b5e5823c0a2dfd260",
                "vout": 27,
                "value": 521513
            }
        ];

        const { inputs, outputs, fee } = coinselection(utxos, recipients, 1, 3);
        expect(fee).toBeGreaterThan(0);
    });
```

**Review by gpa — CHANGES_REQUESTED** [review]
I'm still getting invalid selections, but now its related to the long_term_fee parameter.
```
    test("", () => {
            const recipients = [
                {
                    "value": 78544099,
                    "to": "1DLvZKke9UXK2QwaxnPzQ3Mh8YHu7TsKjS",
                }
            ];
            const utxos = [
            {
                "txId": "7ee0dd32d14fc462e623a5d1cfe38f7412a2f740427f778166131ac9e7950158",
                "vout": 75,
                "value": 864351
            },
            {
                "txId": "2d62424ade769d7f7841d03966877a306e2c039930cbbad36ea3bb6cdf378350",
                "vout": 59,
                "value": 5059
            },
            {
                "txId": "6317f465f13cfd6b907d0715c5bb0f2d87d6f83d14699387f6d39ebbfc453747",
                "vout": 34,
                "value": 1278831
            },
            {
                "txId": "0cdde4f3f5b729642327050b9c9348975b74a9bd8771654c475ea008d527c358",
                "vout": 67,
                "value": 105841088
            },
            {
                "txId": "d78b14b7a40aff897210bbd158687c1c6efefa73515445d16e0ea687ce110cf2",
                "vout": 12,
                "value": 384570
            },
            {
                "txId": "8dfa2f40aca062258aec0f365795a685502beda329d5e7c55db266c955ae1e75",
                "vout": 71,
                "value": 121959
            },
            {
                "txId": "084f26d41457c683d08f78e3bea96e4978f715d912aaf4ec2e55a4baf7abdd60",
                "vout": 29,
                "value": 1063197
            },
            {
                "txId": "3072d49285ac92004f70e091d02cb3fbeefb8127cb6165795a31269462d0f347",
                "vout": 8,
                "value": 1292976
            },
            {
                "txId": "0711f8a8745d6e584c585cb5bfbecd7b85acec4e8281c21b9f354b3b0992533a",
                "vout": 50,
                "value": 1523048
            },
            {
                "txId": "11e8e5901baa2a7eac37d192bbaf20c63ac54b9bffc66b86ef47d130f95fe3f8",
                "vout": 87,
                "value": 116444705
            },
            {
                "txId": "34cceb022593edde49d9d4075060cf32e9323d84c865210098012eacadb8773c",
                "vout": 36,
                "value": 9336
            },
            {
                "txId": "43ceadd80743f7133768e1d9eae5c673c9c1a16621924a6bd0aa996f3a04384c",
                "vout": 29,
                "value": 1192622
            },
            {
                "txId": "fce7846e1b9eff68e777853462b22a04d1f67b690119c4eec89c1aa2f545f9a5",
                "vout": 88,
                "value": 423376
            },
            {
                "txId": "1b0bb27a82a93a0fb60dcac10a882769a8d7199d563b48d93213b0c6736cd897",
                "vout": 19,
                "value": 559328
            },
            {
                "txId": "62590fb8d0f6e04692ce9c8b1f96c4e1dc9192a3fbc19bf824b983b17c458b98",
                "vout": 97,
                "value": 3541
            },
            {
                "txId": "280b6d048c2aa681bcd527148496620533d8eef11ee98edda25981cdd3628a1b",
                "vout": 11,
                "value": 741267
            },
            {
                "txId": "ce6547e727f9e20901a8abfa383d7d8b70e0bc5692d88d9c174f4d9806eecf63",
                "vout": 74,
                "value": 1431470
            },
            {
                "txId": "b657b66deefdca5f7b640811d9e3c90e78f3761be6971b7f9e06dbccf625a643",
                "vout": 51,
                "value": 7049
            },
            {
                "txId": "cdc3450c5e41552270fdc60e87b4fe7fc66f978b9e6791009923581100521902",
                "vout": 54,
                "value": 15380
            },
            {
                "txId": "a54cc2feb63a08da3c9946ec0d930d695c0f1cabf10d4bae4b4bb7b12b58c23f",
                "vout": 31,
                "value": 1981645
            },
            {
                "txId": "8dfe00450a29db2609e21597ee9cd1335ccd4af6d0cae77c0ab429043e4fe913",
                "vout": 37,
                "value": 72795249
            },
            {
                "txId": "ccf742c8edb0020717c179c8bac3efe28498700c4f532b7333fe57e6eedade49",
                "vout": 97,
                "value": 7095
            },
            {
                "txId": "5aa27f69208949188e9de652bf905e307403f4929a96d7f3f6de64b89310de84",
                "vout": 11,
                "value": 6260
            },
            {
                "txId": "116d88f50fba2c5bf0bb1be8080ece41dc4df867809d7d5055bcbae34cdf89d4",
                "vout": 89,
                "value": 511317
            },
            {
                "txId": "0d1efec7bdc4ed9845265e9ed18b0e9ac19c378009214adeafcaf36ca5b002ec",
                "vout": 51,
                "value": 663794
            },
            {
                "txId": "d639c97b14f2c0f0016c0cba7bf75fd61519dd1c507213f29499a4ea96774894",
                "vout": 40,
                "value": 15657
            },
            {
                "txId": "da4ab79aa34f3ac6b60618a366560c6d7d21d851198161703c156a3fbfd77c38",
                "vout": 63,
                "value": 82035389
            },
            {
                "txId": "05ab5d7308333a82bc5b2b806d438e66c9e6648aac490d90e9c32ac12615fc96",
                "vout": 27,
                "value": 301810
            },
            {
                "txId": "443cd864ef20f95bb262301b2da801372adb552220472362526f5b3aa8755d4e",
                "vout": 87,
                "value": 7846
            },
            {
                "txId": "4da51480c21ce1e0deab0578e7fd470d6025cccdf4c69d3b5e5823c0a2dfd260",
                "vout": 27,
                "value": 521513
            }
        ];

        const { inputs, outputs, fee } = coinselection(utxos, recipients, 1, 3);
        expect(fee).toBeGreaterThan(0);
    });
```

**Comment by gpa** [comment]
@brunoerg I will create a new issue since this second problem seems like a problem with the bnb strategy and I also got another case that is invalid.
this one is test passed & lgtm except for the missing fee property as it prevents deconstruction:
 ` ({inputs, outputs, fee} = coinselection(utxo as any, coinSelectRecipients as any, feeRate, feeRate));`

**Review by gpa — APPROVED** [review]

**Comment by brunoerg** [comment]
ok!

**Pull request merged**
